name: On Push

on:
  push:
    branches:
      - master

jobs:
  Update_GH_Pages:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Repository
        uses: actions/checkout@v2
      - name: Installing PHP
        uses: nanasess/setup-php@master
        with:
          php-version: '7.3'
      - name: Generating HTML
        run: |
          php crawl.php $GLOBAL_GH_TOKEN
          cd ../
          git config --global user.email "githubactionbot@gmail.com" && git config --global user.name "Stats Updated"
          PUSH_TO_BRANCH="gh-pages"
          if [ -z "$(git ls-remote --heads https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git ${PUSH_TO_BRANCH})" ]; then
            git clone --quiet https://x-access-token:$GITHUB_TOKEN@github.com/${GITHUB_REPOSITORY}.git $PUSH_TO_BRANCH >/dev/null
            cd $PUSH_TO_BRANCH
            git checkout --orphan $PUSH_TO_BRANCH >/dev/null
            git rm -rf . >/dev/null
            echo "$GITHUB_REPOSITORY" >README.md
            git add README.md
            git commit -a -m "➕ Create $PUSH_TO_BRANCH Branch"
            git push origin $PUSH_TO_BRANCH
            cd ..
            echo "🗃 $PUSH_TO_BRANCH Created"
          else
            echo "👌 $PUSH_TO_BRANCH Clone Log"
            git clone --quiet --branch=$PUSH_TO_BRANCH https://x-access-token:$GITHUB_TOKEN@github.com/${GITHUB_REPOSITORY}.git $PUSH_TO_BRANCH
          fi
          cp -r $GITHUB_WORKSPACE/assets/* $PUSH_TO_BRANCH/assets/
          cp $GITHUB_WORKSPACE/output.html $PUSH_TO_BRANCH/index.html
          cd $PUSH_TO_BRANCH/
          if [ "$(git status --porcelain)" != "" ]; then
            echo "👌 Website Published"
            git add .
            git commit -m "📖 #$GITHUB_RUN_NUMBER - Website Regenerated / ⚡ Triggered By $GITHUB_SHA"
            git push origin $PUSH_TO_BRANCH
          else
            echo "✅ Nothing To Push"
          fi
        env:
          GLOBAL_GH_TOKEN: ${{ secrets.GLOBAL_GH_TOKEN }}